[volume1]
p38.text = """
え あえ いえ うえ おい
うお いわお あおい わお あ い
わ あわ いわ う あう
"""

p42.text = """
あか かう かお かおく かわ
わか あき あおき きか きく
えき おけ こえ いか おか
いきおい きおく うけおい おき おく
"""

p47.text = """
なお なか にあう におう になう にかわ
あかぬけ いなか いけにえ いかに
おこなう わな なわお なう かなう
きを ぬく くに ねこ ねおき
あに あね あにに なにに にわき
こな ねこを かう いなかえ いく
"""