direction = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]
orientation = ["", "L", "R"]
tailtype = ["", "CL", "CR"]
base = [
    "NERSWR", # Shima
    "SWLNEL", # Parx
    "SELNEL", # Ha-sa
    "ERSWR",  # Ma-sa
    "SWLSEL", # Wa
]

[NE.NULL]
text = "ちゃ"

[NEL.NULL]
text = "さ"

[NELCL.NULL]
text = "す"

[NELCL.EL]
text = "すな"
svg = "waseda_su_na.svg"
html = """<img src="{}"><br>NELCL-EL(すな)"""

[NELCL.NE]
text = "すちゃ"

[NELCL.E]
text = "すか"

[NELCL.NER]
text = "すや"

[NELCL.ER]
text = "すま"

[NELCL.SE]
text = "すえ"

[NELCL.SEL]
text = "すは"

[NELCL.SER]
text = "すら"

[NELCL.S]
text = "すう"

[NELCL.SL]
text = "すきゃ"

[NELCL.SW]
text = "すお"

[NELCL.SWL]
text = "すひゃ"

[NELCL.SWR]
text = "すさ"

[NER.NULL]
text = "や"

[E.NULL]
text = "か"

[ECL.NULL]
text = "く"

[EL.NULL]
text = """
あ
な"""

[ER.NULL]
text = """
い
ま"""

[SE.NULL]
text = """え"""

[SEL.NULL]
text = """は"""

[SER.NULL]
text = """ら"""

[SW.NULL]
text = """お"""

[SWL.NULL]
text = """ひゃ"""

