a = """あ あ か"""
ai = """あい"""
aru = """か・ある（点） か・ある（点）・か"""
u = """う"""
e = """え"""
o = """お"""
ka = """か が か・ない否定 かんか"""
kaka = """かか"""
ki = """き"""
ku = """く"""
ke = """け"""
ko = """こ ここnbc a"""
koto = """事 事事"""
kon = """コン・い コン・コン"""
sa = """さ かさ"""
shi = """さ　し　す"""
su = """す"""
ta = """た　たた　たたた　たたたた"""
cha = """ちゃ　ちゃ・ちゃ　ちゃ・ちゃ・ちゃ　ちゃ・ちゃ・ちゃ・ちゃ"""
tacha = """た・た　た・た・た　た・ちゃ　た・た・ちゃ ちゃ・ちゃ　ちゃ・ちゃ・ちゃ・た"""
na = """な"""
nihon = """日本　日本・かい"""
to = """と"""
ha = """は"""
kasaga_nai = """と・かい・て（助詞）・は　し・さつ（交差）・する（点）　わ・か（点）・もの・が　フえ・て（助詞）・いる
けさきた　新聞・の（助詞）・かた（点）・すみに　かい・て（助詞）・いる・た・だけ・と（助詞）・も（助詞）　問題・は
きょう・の（助詞）　雨 かさが・ない（否定） いか・なく（否定）・ちゃ 君に　あい・に　いか・なく（否定）・ちゃ
君・の（助詞）・まつ（交差）・に　いか・なく（否定）・ちゃ 雨に　ぬれ つめ・たい 雨が きょう・は 心に しみる
君・の（助詞）・事 い・かい・は え・られ・なく（否定）・なる それ・は いい・事た・ろう てｒ・ひ・て（助詞）・は わが国・の（助詞） 将来・の（助詞） 問題・を
誰かが  しん・こく・な かお・を・して しゃ・べつ・っ・テｒ た（え略）・と（助詞）・も（助詞） 問題・は きょう・の（助詞） 雨 傘が・ない（否定）

いか・なく（否定）・ちゃ 君に あい・に いか・なく（否定）・ちゃ 君・の（助詞）・うち（交差）・に いか・なく（否定）・ちゃ 雨に ぬれ

つめ・たい 雨が　ほく・の（助詞） め・の（助詞）・なか（点）・に ふｒ 君・の（助詞）・事 い・かい・は
何・も（助詞） みえ・なく（否定）・なる  それ・は いい・事た・ろう

いか・なく（否定）・ちゃ 君に あい・に いか・なく（否定）・ちゃ 君・の（助詞）・まつ（交差）・に いか・なく（否定）・ちゃ 雨に ぬれ

いか・なく（否定）・ちゃ 君に あい・に いか・なく（否定）・ちゃ 君・の（助詞）・うち（交差）・に いか・なく（否定）・ちゃ 雨・の（助詞）・なか（点）・を

いか・なく（否定）・ちゃ 君に あい・に いか・なく（否定）・ちゃ 雨に ぬれ・て（助詞） いか・なく（否定）・ちゃ かさが・ない（否定）
"""
